version: '3.8'

services:
  redis:
    image: redis:7.2.5-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DEFAULT_CONFIG_FILE}:/usr/local/etc/redis/redis.conf
    restart: always
    env_file: .env
    networks:
      - back-tier

  web:
    image: member-management-admin
    container_name: member-management-admin-container
    env_file: .env
    ports:
      - ${SERVER_BINDING_PORT}:${SERVER_PORT}
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - back-tier
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    networks:
      - back-tier

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - back-tier

networks:
  back-tier:
    external: true